App.launchScreens({
  iphone_2x: 'resources/launch_screens/android_xxhdpi_landscape.png',
  iphone5: 'resources/launch_screens/android_xxhdpi_landscape.png',
  iphone6: 'resources/launch_screens/android_xxhdpi_landscape.png',
  iphone6p_portrait: 'resources/launch_screens/android_xxhdpi_landscape.png',
  iphone6p_landscape: 'resources/launch_screens/android_xxhdpi_landscape.png',
  ipad_portrait: 'resources/launch_screens/android_xxhdpi_landscape.png',
  ipad_portrait_2x: 'resources/launch_screens/android_xxhdpi_landscape.png',
  ipad_landscape: 'resources/launch_screens/android_xxhdpi_landscape.png',
  ipad_landscape_2x: 'resources/launch_screens/android_xxhdpi_landscape.png',
  android_mdpi_portrait: 'resources/launch_screens/android_xxhdpi_landscape.png',
  android_mdpi_landscape: 'resources/launch_screens/android_xxhdpi_landscape.png',
  android_hdpi_portrait: 'resources/launch_screens/android_xxhdpi_landscape.png',
  android_hdpi_landscape: 'resources/launch_screens/android_xxhdpi_landscape.png',
  android_xhdpi_portrait: 'resources/launch_screens/android_xxhdpi_landscape.png',
  android_xhdpi_landscape: 'resources/launch_screens/android_xxhdpi_landscape.png',
  android_xxhdpi_portrait: 'resources/launch_screens/android_xxhdpi_landscape.png',
  android_xxhdpi_landscape: 'resources/launch_screens/android_xxhdpi_landscape.png',
});
