App.launchScreens({
  iphone_2x: 'resources/launch_screens/iphone_2x.png',
  iphone5: 'resources/launch_screens/iphone5.png',
  iphone6: 'resources/launch_screens/iphone6.png',
  iphone6p_portrait: 'resources/launch_screens/iphone6p_portrait.png',
  iphone6p_landscape: 'resources/launch_screens/iphone6p_landscape.png',
  ipad_portrait: 'resources/launch_screens/ipad_portrait.png',
  ipad_portrait_2x: 'resources/launch_screens/ipad_portrait_2x.png',
  ipad_landscape: 'resources/launch_screens/ipad_landscape.png',
  ipad_landscape_2x: 'resources/launch_screens/ipad_landscape_2x.png',
  android_mdpi_portrait: 'resources/launch_screens/android_mdpi_portrait.png',
  android_mdpi_landscape: 'resources/launch_screens/android_mdpi_landscape.png',
  android_hdpi_portrait: 'resources/launch_screens/android_hdpi_portrait.png',
  android_hdpi_landscape: 'resources/launch_screens/android_hdpi_landscape.png',
  android_xhdpi_portrait: 'resources/launch_screens/android_xhdpi_portrait.png',
  android_xhdpi_landscape: 'resources/launch_screens/android_xhdpi_landscape.png',
  android_xxhdpi_portrait: 'resources/launch_screens/android_xxhdpi_portrait.png',
  android_xxhdpi_landscape: 'resources/launch_screens/android_xxhdpi_landscape.png',
});

